import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Header from '../components/landing_page/widgets/header'
import Main from '../components/landing_page/screen/main'
import Feature from '../components/landing_page/screen/feature'
import Sample from '../components/landing_page/screen/sample'
export default function LandingPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <Header />
        <Main />
      </main>


      <Feature />
      <Sample />

    </div>
  );
}
